name: acuant_platform_interface
description: A common platform interface for the acuant_flutter plugin.
version: 0.0.4
homepage:

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
